#!/usr/bin/env bash

msg() { echo -e "\e[32mBOOTSTRAPER INFO ---> $1\e[0m"; }
err() { echo -e "\e[31mBOOTSTRAPER ERR ---> $1\e[0m" ; exit 1; }

readonly KUBECONFIG=/root/.kube/config
readonly workingDir="/opt/codefresh"

imagesList=${workingDir}/images
credentials=${workingDir}/token
firebaseCfg=${workingDir}/firebase.yml
dockerCfg=${workingDir}/dockercfg.yml

msg "Waiting credentials..."
while [ ! -e ${credentials} ]; do sleep 1; done

msg "Pulling images..."
dockerPassword=$(base64 -d ${credentials} | head -n-1)
firebaseSecret=$(base64 -d ${credentials} | tail -1)

echo ${firebaseSecret} > ${firebaseCfg}

docker login -u _json_key -p "${dockerPassword}" https://gcr.io || err "Cannot login to docker registry"

for image in $(cat ${imagesList}); do
  docker pull $image
done

kubectl create secret docker-registry dockercfg \
  --docker-server=https://gcr.io \
  --docker-username=_json_key \
  --docker-password="${dockerPassword}" \
  --docker-email=admin@codefresh.io || err "Cannot create docker regestry secret (dockercfg)"

kubectl get secret dockercfg -oyaml | grep 'dockercfg:' | awk -F '.' '{print $2}' > ${dockerCfg}

kubectl delete secret dockercfg