#!/usr/bin/env bash

#uncomment for maintance mode
#exit 0

# run wizard
docker run --restart="always" -d -p 8080:9000 -v /opt/codefresh:/opt/codefresh docker.io/codefresh/enterprise-installer:master

#start bootstrap
wget https://raw.githubusercontent.com/codefresh-io/k8s-single-node-installer/master/images
wget https://raw.githubusercontent.com/codefresh-io/k8s-single-node-installer/master/puller
wget https://raw.githubusercontent.com/codefresh-io/k8s-single-node-installer/master/cf-helm-ami
wget https://raw.githubusercontent.com/codefresh-io/k8s-single-node-installer/master/installer
wget https://raw.githubusercontent.com/codefresh-io/k8s-single-node-installer/master/flannel.yml
wget https://raw.githubusercontent.com/codefresh-io/k8s-single-node-installer/master/local-storage.yml

chmod +x puller
chmod +x installer
chmod +x cf-helm-ami

# install and run k8s
EXTERNAL=true ./installer
mkdir /root/.kube && cp /etc/kubernetes/admin.conf /root/.kube/config

export KUBECONFIG=/root/.kube/config

# run bootstarap
./puller &
./cf-helm-ami &

