#!/bin/bash

# Global env variables / defaults
: ${KUBERNETES_VERSION:=stable-1.7}

# Functions library
os_type() {
	cat /etc/*-release | grep '^NAME' | tr -d 'NAME="'
}

exists() {
	if command -v $1 >/dev/null 2>&1; then
		echo "Command $1 installed"
	else
		echo "Please install $1"
		exit 1
	fi
}

running_as_root() {
	if [[ $EUID > 0 ]]; then
  	echo "Please run as root/sudo"
  	exit 1
	fi
}

enable_bridge_iptables() {
	if [ "$(cat /proc/sys/net/bridge/bridge-nf-call-iptables)" == "0" ]; then
		echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
	fi
}

config_docker_ubuntu() {
	cat << EOF > /etc/docker/daemon.json
{
	"storage-driver": "overlay"
}
EOF
	systemctl restart docker
}

config_docker_centos() {
	cat << EOF > /etc/docker/daemon.json
{
	"exec-opts": ["native.cgroupdriver=systemd"],
	"storage-driver": "overlay"
}
EOF
	systemctl restart docker
}

package_ubuntu() {
	apt-get update && apt-get install -y apt-transport-https
	curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
	cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
	apt-get update
	apt-get install -y kubelet=1.7.11-00 kubeadm=1.7.11-00
}

package_centos() {
	cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
	setenforce 0
	# TODO: Until kubeadm 1.7.2 will be released, we can fix the kubeadm.conf issue by installing kubeadm=1.7.0-00
	yum install -y kubelet-1.7.11-0 kubeadm-1.7.11-0
	systemctl enable kubelet && systemctl start kubelet
}

rhel_iptables(){
  setenforce 0
  yum install iptables-services.x86_64 -y
  systemctl start iptables
  systemctl enable iptables
  systemctl unmask iptables
  iptables -F
  service iptables save
}

check_iptables(){

  if command -v iptables >/dev/null 2>&1; then
    echo "iptables installed"
  else
		echo "iptables is not installed"
		read -p "Do you want to install iptables (y/n)" yn
		case ${yn} in
      y|Y )
          rhel_iptables
      ;;
      * )
          echo "k8s can't run without iptables, please install it manually"
          exit 1
      ;;
    esac
	fi

}

# Phase 1 - Pre-flight checks

# 1. Are we running as root or sudo?
running_as_root

# 2. Docker exists?
exists "docker"

# 3. Nsenter utility exists?
exists "nsenter"


# Phase 2 - install kubernetes and kubeadm packages
case "$(os_type)" in
	*Ubuntu*)
		config_docker_ubuntu
		package_ubuntu
		;;
	*CentOS*)
		enable_bridge_iptables
		config_docker_centos
		package_centos
		;;
	*Red*)
		check_iptables
		enable_bridge_iptables
		config_docker_centos
		package_centos
		;;
	*)
		fail
		;;
esac

EXTERNAL=${EXTERNAL:-false}
TOKEN=$(kubeadm token generate | tee kubeadm.token)
IDENT_ME=$(curl ident.me)
API_URL=${API_URL:-$IDENT_ME}
APISERVER_CERT_SANS=${APISERVER_CERT_SANS:-$API_URL}
POD_NETWORK_CIDR=${POD_NETWORK_CIDR:-"10.244.0.0/16"}

# Enable alpha APIs
if [[ "${EXTERNAL}" == "true" ]]; then
cat <<EOF >/etc/kubernetes/kubeadm.conf
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: "${KUBERNETES_VERSION}"
token: ${TOKEN}
tokenTTL: "0"
networking:
  podSubnet: ${POD_NETWORK_CIDR}
apiServerExtraArgs:
  "feature-gates": "PersistentLocalVolumes=true"
controllerManagerExtraArgs:
  "feature-gates": "PersistentLocalVolumes=true"
schedulerExtraArgs:
  "feature-gates": "AffinityInAnnotations=true"
apiServerCertSANs:
- ${APISERVER_CERT_SANS}
EOF
else
cat <<EOF >/etc/kubernetes/kubeadm.conf
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: "${KUBERNETES_VERSION}"
token: ${TOKEN}
tokenTTL: "0"
networking:
  podSubnet: ${POD_NETWORK_CIDR}
apiServerExtraArgs:
  "feature-gates": "PersistentLocalVolumes=true"
controllerManagerExtraArgs:
  "feature-gates": "PersistentLocalVolumes=true"
schedulerExtraArgs:
  "feature-gates": "AffinityInAnnotations=true"
EOF
fi

# Phase 3 - initialize the Kubernetes cluster
kubeadm init --config /etc/kubernetes/kubeadm.conf | tee kubeadm.log | grep -P '^\[' --color=never

# Remove master taints to make master schedulable for pods
export KUBECONFIG=/etc/kubernetes/admin.conf

kubectl taint nodes --all dedicated-
kubectl taint nodes --all node-role.kubernetes.io/master-

# Install networking. Even in single-node mode, before the master node will become
# available for scheduling (Ready), it should detect a network plugin configuration.
kubectl create -f flannel.yml

# TODO: Move the addons such as the provisioner to the helm package
# Grant admin permissions to the default serviceaccount in the codefresh namespace
kubectl create namespace codefresh
kubectl create clusterrolebinding codefresh-default-cluster-admin --clusterrole=cluster-admin --serviceaccount=codefresh:default
kubectl create clusterrolebinding kube-system-default-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default

# Create the host-path pvc provisioner
# Starting from Kubernetes version 1.7, a local provisioner plugin is supported, however it's still in alpha.
kubectl --namespace codefresh create -f local-storage.yml
mkdir -p /var/local-volume-provisioner/disks/{1..20}

cat << 'END'
Your single-node Kubernetes cluster has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

END

tail -n5 kubeadm.log
